/* CUSP build: validates actors.json against schema.json, then regenerates
 * data.js and the two standalone HTML bundles. Run after ANY data edit:
 *   node cusp/build.js
 * Fails (exit 1) on any invalid record, so bad data can't ship.
 */
const fs = require("fs");
const path = require("path");
const DIR = __dirname;

const schema = JSON.parse(fs.readFileSync(path.join(DIR, "schema.json"), "utf8"));
const { version, generated, actors } = JSON.parse(fs.readFileSync(path.join(DIR, "actors.json"), "utf8"));
const E = schema.enums;
const errs = [];
const chk = (id, cond, msg) => { if (!cond) errs.push(`${id}: ${msg}`); };

const ids = new Set(actors.map(a => a.id));
chk("dataset", ids.size === actors.length, "duplicate ids");

for (const a of actors) {
  for (const f of schema.required) chk(a.id, f in a, `missing field ${f}`);
  chk(a.id, E.actorType.includes(a.actorType), `bad actorType ${a.actorType}`);
  chk(a.id, E.activity.includes(a.activity), `bad activity ${a.activity}`);
  chk(a.id, E.orientation.includes(a.orientation), `bad orientation`);
  chk(a.id, E.interestFocus.includes(a.interestFocus), `bad interestFocus`);
  chk(a.id, E.positioning.includes(a.positioning), `bad positioning`);
  chk(a.id, E.explicitness.includes(a.explicitness), `bad explicitness`);
  chk(a.id, E.confidence.includes(a.confidence), `bad confidence`);
  chk(a.id, E.status.includes(a.status), `bad status`);
  chk(a.id, ["s4d","d4s","SinD","DinS"].every(t => E.fit.includes(a.sdTypeFit?.[t])), `bad sdTypeFit`);
  chk(a.id, Array.isArray(a.tools) && a.tools.every(t => E.tools.includes(t)), `bad tools`);
  chk(a.id, Array.isArray(a.objectiveCodes) && a.objectiveCodes.length > 0 &&
            a.objectiveCodes.every(c => E.objectiveCodes.includes(c)), `bad/empty objectiveCodes`);
  chk(a.id, Array.isArray(a.relations) && a.relations.every(r => E.relationType.includes(r.type)), `bad relation type`);
  chk(a.id, Array.isArray(a.sources) && a.sources.length > 0 &&
            a.sources.every(s => /^https?:\/\//.test(s.url) && s.title && s.accessed), `bad/empty sources`);
  chk(a.id, a.foundedYear === null || Number.isInteger(a.foundedYear), `bad foundedYear`);
  chk(a.id, a.sdSinceYear === null || Number.isInteger(a.sdSinceYear), `bad sdSinceYear`);
  for (const d of ["strategic","operational","enabling","conduct"])
    chk(a.id, Number.isInteger(a.alignment?.[d]) && a.alignment[d] >= 0 && a.alignment[d] <= 3, `bad alignment.${d}`);
  chk(a.id, typeof a.alignment?.note === "string" && a.alignment.note.length > 0, `missing alignment.note`);
  // internal relation targets must resolve
  a.relations.forEach(r => {
    if (/^[a-z]{2}-|^x-|^eu-/.test(r.to) && r.to.length < 16 && !r.to.includes(" "))
      chk(a.id, ids.has(r.to), `relation target '${r.to}' looks like an id but doesn't exist`);
  });
}

if (errs.length) { console.error(`INVALID (${errs.length}):\n` + errs.join("\n")); process.exit(1); }

/* ---- generate data.js (apps consume this; includes compat fields) ---- */
const appActors = actors.map(a => ({
  ...a,
  // compat for index.html/survey.html
  sdType: ["s4d","d4s","SinD","DinS"].filter(t => ["A","B"].includes(a.sdTypeFit[t])),
  sinceYear: a.sdSinceYear ?? a.foundedYear
}));
const banner = `/* GENERATED by build.js from actors.json (v${version}) — DO NOT EDIT.\n * Edit actors.json, then run: node cusp/build.js */\n`;
fs.writeFileSync(path.join(DIR, "data.js"),
  banner +
  `const DATASET=${JSON.stringify({ version, generated, count: actors.length })};\n` +
  `const OBJECTIVE_LABELS=${JSON.stringify(schema.objectiveCodeLabels)};\n` +
  `const ACTORS=${JSON.stringify(appActors, null, 1)};\n`);

/* ---- regenerate standalones ---- */
const data = fs.readFileSync(path.join(DIR, "data.js"), "utf8");
for (const [src, out] of [["index.html","cusp-standalone.html"],["survey.html","survey-standalone.html"]]) {
  const html = fs.readFileSync(path.join(DIR, src), "utf8")
    .replace('<script src="data.js"></script>', "<script>\n" + data + "\n</script>");
  if (!html.includes("const ACTORS")) { console.error(`inline failed for ${src}`); process.exit(1); }
  fs.writeFileSync(path.join(DIR, out), html);
}
console.log(`OK: ${actors.length} records valid · data.js + 2 standalones regenerated (dataset v${version}, ${generated})`);
